/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cnfts.types";
import * as _1 from "./Cnfts.client";
import * as _2 from "./Cnfts.react-query";
import * as _3 from "./Cnfts.recoil";
export namespace contracts {
  export const Cnfts = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}